In [1]:
import numpy as np

def sinkhorn_regularized(C, mu1, mu2, mu3, lambda_reg, max_iters=1000):
    K = np.exp(-lambda_reg * C)
    u1 = np.ones_like(mu1)
    u2 = np.ones_like(mu2)
    u3 = np.ones_like(mu3)

    for _ in range(max_iters):
        u = mu1 / (K @ v)
        v = mu2 / (K.T @ u)

    T = np.diag(u) @ K @ np.diag(v)
    return T


In [5]:
C = np.array([[2, 1, 3], [5, 4, 2], [3, 1, 4]])
a = np.array([0.3, 0.2, 0.5])
b = np.array([0.1, 0.4, 0.5])
lambda_reg = 0.1

T = sinkhorn_regularized(C, a, b, lambda_reg)

print(T)

[[0.03188796 0.12106066 0.14705138]
 [0.01712917 0.06502983 0.11784101]
 [0.05098287 0.21390951 0.23510762]]
